= Methods
This study deployed DQN and contextual bandits on the UCI Heart Disease-dataset to compare their predictive performance, bias and fairness between different patient groups. Both models can learn from sequential experiences, but they differ in how they balance exploration and exploitation and their approaches for policy optimization. The purpose of using the same dataset is to evaluate not only the overall predictive accuracy but also models perform with different categories and groups, particularly focusing on the sex-related differences. // age-related too
This comparative method gives insight into the trade-offs between model complexity, predictive power, and fairness. 

The dataset used was UCI Heart Disease-data, which contains both numerical and categorical patient features as well as a target variable, which indicates the degree of heart disease severity. Preprocessing included removal of irrelevant columns and handling missing values trough imputing numerical values with median and categorical with mode. Categorical values were one-hot encoded with first category dropped to avoid redundancy and numeric features were standardized using `StandardScaler`. Data was split into training and testing sets with a 80:20 split and stratification to preserve class distribution. `SMOTE` (Synthetic Minority Oversampling Techniques) was used to handle class imbalances by generating synthetic examples. // add info that SMOTE was additional dataset, information about age bins were extracted for age sub-group analysis, more details about what was deleted 

We used a deep reinforcement learning model for DQN to predict heart dieses from patient features. DQN combines Q-learning with deep neural networks to estimate the expected reward for different actions in a given state. Although traditionally used for sequential decision-making tasks, in this case it was used for classification, allowing model to learn from imbalanced dataset by replaying past experiences and updating its policy iteratively. This approach is especially useful in clinical datasets where classes and subgroups are underrepresented, because it can learn from rare cases without being overwhelmed by majority-class examples. 

DQN-model was trained for `40 epochs `with an experience relay buffer increasing up to 20 000 samples. To stabilize learning and prevent network form overfitting, the relay buffer is important as it stores previous experiences and samples them randomly. Furthermore, this mechanism also allows the model to repeat rare cases. An exploration rate (`epsilon`) of 0,05 was used during training to ensure the model explores more uncommon actions. This encourages exploration of underexplored classes, which strengthens ability to generalize. The steady decrease of average loss per epoch suggestes that the DQN-model converged successfully. 

Model performance was evaluated with accuracy and macro F1 score to give indication of predictive abilities. In addition, sex-based evaluation metrics and confusion matrices were computed to assess possible female and male differences. This analysis helped quantify both DQN-models predictive ability and its fairness, providing solid ground for comparison of other reinforcement learning model. 
